name: Custom Env Variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR_1: "Workflow level variable"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VAR_2: "Job level variable value"

    steps:

      - name: write value to $GITHUB_ENV file
        run: echo "VAR_1=value set from first step" >> "$GITHUB_ENV"

      - name: display value of VAR_1
        env:
          VAR_2: "override Job level variable value"
        run: |
          echo "Value of VAR_1 is $VAR_1"
          echo "Value of VAR_2 is $VAR_2"

      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: |
          echo "The selected color is $SELECTED_COLOR"
          echo "Value of VAR_2 is $VAR_2"
